# we're in php baby
language: php

# php versions to test on
php:
  - 5.5
  - 5.4

# setup composer
before_script:
  - composer install
  - composer dump-autoload -o
  - cp config.travis.json config.json

# tests  
script: phpunit