<?php namespace Petflow\Litle\Transaction\Request;

use Petflow\Litle\Exception;
use Petflow\Litle\ResponseCode;
use Petflow\Litle\Transaction\Response;

/**
 * Auth Reversal Transaction
 *
 * @author Nate Krantz <nate@petflow.com>
 * @copyright Petflow.com 2013
 */
class AuthorizationReversalRequest extends TransactionRequest {

	/**
	 * Make an Authoirzation Reversal Transaction
	 *
	 * When providing the parameters for an auth reversal, the
	 * request must have a txnId that was generated by a prior
	 * authorization request. Additionally, an actionReason
	 * can be provided for suspect fraud:
	 *
	 * 	'actionReason' => 'SUSPECT_FRAUD'
	 *
	 * The request should NOT contain an amount parameter, unless
	 * the clients system wants to do partial auth reversal.
	 */
	public function make($params) {

		// there must be a transaction id provided in the request
		// so that we can make the reversal
		if (!isset($params['litleTxnId'])) {
			throw new Exception\MissingRequestParameterException('litleTxnId');
		}

		// there must be an order id, which we use to tie the
		// request back to our merchant's system
		if (!isset($params['orderId'])) {
			throw new Exception\MissingRequestParameterException('orderId');
		}

		// stop any amounts, so that we can prevent partial
		// reversal until client system supports it
		if (isset($params['amount']))  {
			unset($params['amount']);
		}

		if ($this->mode == 'APPROVED') {
			$params['litleTxnId'] = (string) $params['litleTxnId'].'000';
		}

		return $this->respond(
			$this->litle_sdk->authReversalRequest($params)
		);
	}

	/**
	 * Respond to the Auth Reversal Transaction
	 *
	 * The response to an auth reversal should contain the 
	 * orderId provided, response code, messsage, response time
	 * and the litletxnid assoicated with the reversal.
	 *
	 * We can further produce more information about the response
	 * by using the TransactionResponseCode with the provided
	 * response.
	 */
	public function respond($raw_response) {
		return new Response\AuthorizationReversalResponse($raw_response);
	}

}